### ISSUE TITLE
simon

### ISSUE THREAD

**Issue by osk-osk** [vesselinux/yaarx#1]
hello, 
dear Mr. Biryukov ,i am a ms student from iran . i need your help.  i don't know what to say but if its possible for you please help me. i need your simulation codes of   "differential analysis  of Simon and speck families of block ciphers" paper.
help me if you can.
thank you

**Comment by vesselinux** [comment]
Dear osk-osk,

The requested code is now added at:

 yaarx/tests/speck-xor-threshold-search-tests.cc
 yaarx/tests/simon-xor-threshold-search-tests.cc

Regards,
vesselinux
